# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 16:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20161004_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None),
        ),
    ]
