# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20161004_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfeed',
            old_name='content',
            new_name='image',
        ),
    ]
