# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20161004_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfeed',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='dashboard.Report'),
        ),
    ]
