# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 02:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20161004_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfeed',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportitem',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='ReportFeed',
        ),
        migrations.DeleteModel(
            name='ReportItem',
        ),
    ]
