# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='module',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
