# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20161114_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='acknowledged',
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('U', 'Unseen'), ('V', 'Viewed'), ('F', 'Fixed')], default='U', max_length=1),
        ),
    ]
