# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20170503_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
    ]
