# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 02:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20170504_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
